# title of website
title: ybyml导航

# description of website
description: ybyml's navigation site

# favicon of website
favicon: "https://github.com/ybyml.png?size=40"

# your website url
url: https://ybyml.github.io/ybyml.github.io/

# github profile url
github: "https://github.com/ybyml"

# footer message
footer: © 2021-2021 @ybyml

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: yeelogo
          description: yeelogo在线图标制作平台。
          url: http://yeelogo.com/#/
        - name: v2ex
          description: v2ex技术社区。
          url: https://www.v2ex.com/
        - name: sov2ex
          description: 一个便捷的 v2ex 站内搜索引擎
          url: https://www.sov2ex.com/     
        - name: 发现什么值得买
          description: 分享购物平台。
          url: https://faxian.smzdm.com/
        - name: 西瓜视频
          description: 西瓜视频关注最新
          url: https://www.ixigua.com/my/attention/new
        - name: 京东
          description: 大家都知道的购物站点
          url: https://www.jd.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 淘宝
          description: 淘东西的地方
          url: https://www.taobao.com/
        - name: CCF
          description: CCF二手区
          url: https://bbs.et8.net/bbs/forumdisplay.php?f=174&pp=35&sort=dateline&order=desc&daysprune=45
    - name: 软件相关
      sites:
        - name: 果核剥壳
          description: 互联网的净土
          url: https://www.ghxi.com/
        - name: 卡饭论坛
          description: 浏览器%杀毒等
          url: https://bbs.kafan.cn/forum.php
        - name: 未来软件园
          description: 常用的软件站
          url: http://www.orsoon.com/
        - name: 大眼仔旭
          description: 图像影视处理软件
          url: http://www.dayanzai.me/
        - name: zd423
          description: 软件分享平台领跑
          url: https://www.zdfans.com/
        - name: 小众软件
          description: 分享免费、小巧、实用等
          url: https://www.appinn.com/
        - name: dailydownloaded
          description: 好像是一个国外的软件站
          url: http://windows.dailydownloaded.com/zh/
    - name: VPS&SSR
      sites:
        - name: 甲骨文
          description: 免费中的强大vps（推荐）
          url: https://www.oracle.com/cn/cloud/
        - name: getafreenode
          description: Get A Free Node
          url: https://getafreenode.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
    - name: 网站工具
      sites:
        - name: Cloudflare
          description: 全球最大网络服务商
          url: https://dash.cloudflare.com/login/
        - name: freenom
          description: 免费域名服务商
          url: https://www.freenom.com/zh/index.html?lang=zh
        - name: eu.org
          description: 永久免费域名
          url: https://nic.eu.org/arf/en/
    - name: 扬州大学
      sites:
        - name: 扬大主页
          description: yangzhou University
          url: https://www.yzu.edu.cn/index.htm
        - name: 扬大融合门户
          description: 个人门户入口
          url: https://i.yzu.edu.cn
        - name: Eol平台
          description: 在线教学平台
          url: http://eol.yzu.edu.cn/meol/index.do
        - name: 建工
          description: 学院
          url: https://jgxy.yzu.edu.cn/index.htm
        - name: 学校VPN平台
          description: 在线学校VPN平台
          url: https://webvpn.yzu.edu.cn/login
        - name: 图书馆检索
          description: 图书馆检索平台系统
          url: http://opac.yzu.edu.cn:8080/reader/login.php
        - name: 在线教学登记
          description: 在线教学登记平台
          url: http://melab.yzu.edu.cn/jwc/online_edu_pause.asp
        - name: 信息中心
          description: 信息中心软件平台
          url: https://xxhc.yzu.edu.cn/zbrj/
    - name: Google产品
      sites:
        - name: Google相册
          description: 长期备份手机照片的地方
          url: https://photos.google.com/
        - name: Gmail
          description: 国外邮箱（缺少不了的）
          url: https://mail.google.com/
        - name: Google keep
          description: Google方便记事本
          url: https://keep.google.com/u/0/
        - name: Google voice
          description: GV电话信息
          url: https://voice.google.com/
        - name: Google 日历
          description: Google记事提醒
          url: https://calendar.google.com/
        - name: Youtube
          description: Google视频平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的搜索引擎
          url: https://www.google.com/
        - name: twitter
          description: 推特
          url: https://twitter.com/home
    - name: 发现产品
      sites:
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
        - name: Material icons
          description: Access over 900 material system icons, available in a variety of sizes and densities, and as a web font.
          url: https://material.io/icons/
        - name: Simpleline Icons
          description: Simple line Icons pack
          url: http://simplelineicons.com/
    - name: 摄影图库
      sites:
        - name: wallhaven
          description: 最喜欢的图片库
          url: https://wallhaven.cc/
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml

